apiVersion: v1
kind: Namespace
metadata:
  name: dl-database
  labels:
    app.kubernetes.io/part-of: digitallead-platform
    app.kubernetes.io/managed-by: kubectl
    digitallead.com.br/environment: shared
    digitallead.com.br/purpose: database

    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
