apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup
  namespace: dl-database
  labels:
    app.kubernetes.io/name: postgresql-backup
    app.kubernetes.io/part-of: digitallead-platform
    digitallead.com.br/purpose: backup
  annotations:
    digitallead.com.br/external-backup-required: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dl-local-retain
  resources:
    requests:
      storage: 20Gi
