# Default values for Graylog.

# Kubernetes provider (optional)
provider: ""

# Override Graylog and Graylog Data Node version (optional)
version: ""

# Override the chart name (optional)
nameOverride: ""

# Override the (fully qualified) app name (optional)
fullnameOverride: ""

# Overrides values for Graylog, Datanode, and MongoDB
global:
  imagePullSecrets: []
  existingSecretName: ""
  storageClass: ""

# Graylog application
graylog:
  enabled: true
  enterprise: true
  replicas: 2
  service:
    nameOverride: ""
    type: ClusterIP
    ports:
      app: 9000
      metrics: 9833
    metrics:
      enabled: true
  inputs:
    - name: input-gelf
      port: 12201
      targetPort: 12201
      protocol: TCP
    - name: input-forwarder
      port: 13301
      targetPort: 13301
      protocol: TCP
  plugins: []
  env: {}
  # Graylog server configuration (server.conf)
  config:
    rootUsername: "admin"
    rootPassword: ""
    customSecretPepper: ""
    timezone: "UTC"
    selfSignedStartup: "true"
    serverJavaOpts: "-Xms1g -Xmx1g"
    extraServerJavaOpts: []
    leaderElectionMode: "automatic"
    contentPacksAutoInstall: "true"
    isCloud: "false"
    tls:
      enabled: false
      secretName: ""
      keyPassword: ""
      updateKeyStore: true
      keyStorePass: "changeit"
    mongodb:
      customUri: ""
      maxConnections: "1000"
      versionProbeAttempts: "0"
    messageJournal:
      enabled: "true"
      flushAge: "1m"
      flushInterval: "1000000"
      maxAge: "12h"
      segmentAge: "1h"
      segmentSize: "100mb"
    network:
      connectTimeout: "5s"
      enableCors: "false"
      enableGzip: "true"
      maxHeaderSize: "8192"
      readTimeout: "10s"
      threadPoolSize: "64"
      externalUri: ""
    performance:
      asyncEventbusProcessors: "2"
      autoRestartInputs: "false"
      inputBufferProcessors: "2"
      inputBufferRingSize: "65536"
      inputBufferWaitStrategy: "blocking"
      jobSchedulerConcurrencyLimits: ""
      outputBatchSize: "500"
      outputFaultCountThreshold: "5"
      outputFaultPenaltySeconds: "30"
      outputFlushInterval: "1"
      outputBufferProcessorThreadsCorePoolSize: "3"
      outputBufferProcessors: ""
      processBufferProcessors: ""
    email:
      enabled: "false"
      senderAddress: "graylog@example.com"
      hostname: "mail.example.com"
      port: "587"
      socketConnectionTimeout: "10s"
      socketTimeout: "10s"
      useAuth: "true"
      useSsl: "false"
      useTls: "true"
      webInterfaceUrl: "https://graylog.example.com"
    plugins:
      enabled: false
    geolocation:
      enabled: false
      maxmindGeoIp:
        enabled: true
        accountId:
        licenseKey:
        cronSchedule: "0 0 * * *"
        postInstallRun: true
      mmdbSources:
        city:
          url:
          checksum:
        asn:
          url:
          checksum:
    init:
      assetFetch:
        enabled: false
        skipChecksum: false
        allowHttp: false
        plugins:
          enabled: false
          baseUrl:
        geolocation:
          enabled: false
          baseUrl:
  image:
    repository: ""
    tag: ""
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      partition:
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  persistence:
    enabled: true
    storageClass:
    volumeNameOverride:
    existingClaim:
    mountPath:
    accessModes: []
    size:
    annotations: {}
    labels: {}
    selector: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnv: []

# Graylog Datanode
datanode:
  enabled: true
  replicas: 3
  service:
    ports:
      api: 8999
      data: 9200
      config: 9300
  env: {}
  config:
    nodeIdFile: ""
    opensearchHeap: "2g"
    javaOpts: "-Xms1g -Xmx1g"
    skipPreflightChecks: "false"
    nodeSearchCacheSize: "10gb"
    s3ClientDefaultSecretKey: ""
    s3ClientDefaultAccessKey: ""
    s3ClientDefaultEndpoint: ""
    s3ClientDefaultRegion: "us-east-2"
    s3ClientDefaultProtocol: "http"
    s3ClientDefaultPathStyleAccess: "true"
  image:
    repository: ""
    tag: ""
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      partition:
  resources:
    limits:
      cpu: "1"
      memory: "5Gi"
    requests:
      cpu: "500m"
      memory: "3.5Gi"
  persistence:
    enabled: true
    data:
      enabled: true
      storageClass: ""
      existingClaim: ""
      mountPath: ""
      accessModes: []
      size: "8Gi"
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}
    nativeLibs:
      enabled: false
      storageClass: ""
      existingClaim: ""
      mountPath: ""
      accessModes: []
      size: "2Gi"
      annotations: {}
      labels: {}
      selector: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podDisruptionBudget:
    enabled: false
    minAvailable: 2
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnv: []

# Graylog service account
serviceAccount:
  create: true
  automount: true
  annotations: {}
  nameOverride: ""
  role:
    create: false
    rules: []
#      - apiGroups: [ "" ]
#        resources: [ "pods" ]
#        resourceNames: []
#        verbs: [ "get" ]
# Ingress configuration
# more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  config:
    defaultBackend:
      enabled: true
    tls:
      clusterIssuer:
        existingName:
      issuer:
        existingName:
        managed:
          enabled: false
          staging: true
  web:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  forwarder:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

# MongoDB Community Resource configuration
# Requires MongoDB Kubernetes Operator: https://github.com/mongodb/mongodb-kubernetes/tree/master/docs/mongodbcommunity
mongodb:
  communityResource:
    enabled: true
  version: "7.0.25"
  replicas: 2
  arbiters: 1
  persistence:
    storageClass: ""
    size:
      data: "10G"
      logs: "2G"
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    nameOverride: ""
    role:
      create: true
      rules:
        - apiGroups: [ "" ]
          resources: [ "secrets" ]
          resourceNames: [ ]
          verbs: [ "get" ]
        - apiGroups: [ "" ]
          resources: [ "pods" ]
          resourceNames: [ ]
          verbs: [ "get", "patch", "delete" ]
