apiVersion: platform.digitallead.com.br/v1alpha1
kind: HelmComponent

metadata:
  id: PLT-701
  name: graylog
  description: Plataforma centralizada de logs da Digitalead

release:
  name: graylog
  namespace: dl-logging

chart:
  repository:
    name: graylog
    url: https://graylog2.github.io/graylog-helm

  name: graylog
  version: 1.0.0

values:
  file: values.yaml
