global:
  storageClass: dl-local-retain

graylog:
  enabled: true
  enterprise: false
  replicas: 1

  service:
    type: ClusterIP

    ports:
      app: 9000
      metrics: 9833

    metrics:
      enabled: true

  inputs:
    - name: input-gelf
      port: 12201
      targetPort: 12201
      protocol: TCP

    - name: input-forwarder
      port: 13301
      targetPort: 13301
      protocol: TCP

  config:
    rootUsername: admin

    # Não commitar valores reais.
    rootPassword: "gi0b5wUdvTSOiU1aVdcV8BaAl6YbcLob"
    customSecretPepper: "205a0da58472cdc8fdcbea0c73b723005b59bb19fc355ff50fc31cff57bf3fa15f813c88a1b30e790eda3c6f47028896"

    timezone: America/Sao_Paulo

    # Certificado interno autogerado entre Graylog e Data Nodes.
    selfSignedStartup: "true"

    serverJavaOpts: "-Xms1g -Xmx1g"
    extraServerJavaOpts: []

    leaderElectionMode: automatic
    contentPacksAutoInstall: "true"
    isCloud: "false"

    tls:
      # TLS público termina no Traefik.
      enabled: false
      secretName: ""
      keyPassword: ""
      updateKeyStore: false
      keyStorePass: changeit

    mongodb:
      customUri: ""
      maxConnections: "100"
      versionProbeAttempts: "20"

    messageJournal:
      enabled: "true"
      flushAge: 1m
      flushInterval: "1000000"
      maxAge: 12h
      segmentAge: 1h
      segmentSize: 100mb

    network:
      connectTimeout: 5s
      enableCors: "false"
      enableGzip: "true"
      maxHeaderSize: "8192"
      readTimeout: 10s
      threadPoolSize: "32"
      externalUri: ""

    performance:
      asyncEventbusProcessors: "2"
      autoRestartInputs: "true"
      inputBufferProcessors: "2"
      inputBufferRingSize: "65536"
      inputBufferWaitStrategy: blocking
      jobSchedulerConcurrencyLimits: ""
      outputBatchSize: "500"
      outputFaultCountThreshold: "5"
      outputFaultPenaltySeconds: "30"
      outputFlushInterval: "1"
      outputBufferProcessorThreadsCorePoolSize: "2"
      outputBufferProcessors: ""
      processBufferProcessors: ""

    email:
      enabled: "false"

    plugins:
      enabled: false

    geolocation:
      enabled: false

  env: {}
  extraEnv: []
  plugins: []

  resources:
    requests:
      cpu: 250m
      memory: 1536Mi
    limits:
      cpu: "2"
      memory: 3Gi

  persistence:
    enabled: true
    storageClass: dl-local-retain
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 8
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 8
    successThreshold: 1

  podDisruptionBudget:
    enabled: false
    minAvailable: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}

datanode:
  enabled: true
  replicas: 1

  config:
    nodeIdFile: ""

    # Não aumentar baseado na RAM do host.
    # O valor deve respeitar o limite de memória do Pod.
    opensearchHeap: 2g

    javaOpts: "-Xms512m -Xmx512m"
    skipPreflightChecks: "false"
    nodeSearchCacheSize: 2gb

    s3ClientDefaultSecretKey: ""
    s3ClientDefaultAccessKey: ""
    s3ClientDefaultEndpoint: ""
    s3ClientDefaultRegion: us-east-2
    s3ClientDefaultProtocol: http
    s3ClientDefaultPathStyleAccess: "true"

  env: {}
  extraEnv: []

  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: "2"
      memory: 5Gi

  persistence:
    enabled: true

    data:
      enabled: true
      storageClass: dl-local-retain
      accessModes:
        - ReadWriteOnce
      size: 40Gi
      existingClaim: ""
      mountPath: ""
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}

    nativeLibs:
      enabled: false
      storageClass: dl-local-retain
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""
      mountPath: ""
      annotations: {}
      labels: {}
      selector: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 8
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 8
    successThreshold: 1

  podDisruptionBudget:
    enabled: false
    minAvailable: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  enabled: true

  config:
    defaultBackend:
      enabled: false

    tls:
      clusterIssuer:
        existingName: letsencrypt-production

      issuer:
        existingName: ""

        managed:
          enabled: false
          staging: false

  web:
    enabled: true
    className: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production

    hosts:
      - host: graylog.app.digitallead.com.br
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: graylog-tls
        hosts:
          - graylog.app.digitallead.com.br

  forwarder:
    enabled: false
    className: ""
    annotations: {}
    hosts: []

mongodb:
  communityResource:
    enabled: true

  version: "7.0.25"

  replicas: 1
  arbiters: 0

  persistence:
    storageClass: dl-local-retain

    size:
      data: 10G
      logs: 2G

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    nameOverride: ""

    role:
      create: true

      rules:
        - apiGroups:
            - ""
          resources:
            - secrets
          resourceNames: []
          verbs:
            - get

        - apiGroups:
            - ""
          resources:
            - pods
          resourceNames: []
          verbs:
            - get
            - patch
            - delete
